######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 30 13:48:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
SOURCES += main.cpp
